<?php

namespace AppBundle\Repository;

/**
 * SharedResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharedResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
